# Reference image
FROM nginx:1.25.5@sha256:a484819eb60211f5299034ac80f6a681b06f89e65866ce91f356ed7c72af059c

# Metadata
LABEL org.opencontainers.image.authors="Daniel Wydler"

#
CMD ["nginx", "-g", "daemon off;"]
