# Reference image
FROM docker.elastic.co/kibana/kibana:8.19.12@sha256:e11aecaca4efaed10493e05a5ad9c051b3cb32deca2db4aba74c0687e83ab677

# Metadata
LABEL maintainer="Daniel Wydler"
LABEL org.opencontainers.image.authors="Daniel Wydler"
LABEL org.opencontainers.image.description="A Python package and CLI for parsing aggregate and forensic DMARC reports."
LABEL org.opencontainers.image.documentation="https://github.com/dwydler/parsedmarc-docker/blob/master/README.md"
LABEL org.opencontainers.image.source="https://github.com/dwydler/parsedmarc-docker"
LABEL org.opencontainers.image.title="wydler/parsedmarc-kibana"
LABEL org.opencontainers.image.url="https://github.com/dwydler/parsedmarc-docker"


