# Reference image
FROM wydler/logrotate:1.2.4@sha256:fc895524ee87770eb65e6a5102a314c65f9f3ddbf6bef688d3a9a2b347de6ff6

# Metadata
LABEL maintainer="Daniel Wydler"
LABEL org.opencontainers.image.authors="Daniel Wydler"
LABEL org.opencontainers.image.description="A Python package and CLI for parsing aggregate and forensic DMARC reports."
LABEL org.opencontainers.image.documentation="https://github.com/dwydler/parsedmarc-docker/blob/master/README.md"
LABEL org.opencontainers.image.source="https://github.com/dwydler/parsedmarc-docker"
LABEL org.opencontainers.image.title="wydler/parsedmarc-logrotate"
LABEL org.opencontainers.image.url="https://github.com/dwydler/parsedmarc-docker"
