---
name: Build & publish docker images

"on":
  workflow_dispatch:
    inputs:
      softwarebuild:
        type: choice 
        required: false
        options: 
          - release
          - snapshot
        default: "release"
  release:
    types:
      - released
      - prereleased

permissions:
  contents: read

env:
  REGISTRY: ${{ vars.REGISTRY }}
  REGISTRY_ACCOUNT: ${{ vars.REGISTRY_ACCOUNT }}
  REGISTRY_REPO: ${{ vars.REGISTRY_REPO }}
  REGISTRY_REPO_TAG_CACHE_NAME: ${{ vars.REGISTRY_REPO_TAG_CACHE_NAME }}
  REGISTRY_PLATFORMS: ${{ vars.REGISTRY_PLATFORMS }}
  
  SOFTWARE_BUILD: ${{ github.event.inputs.softwarebuild  || 'release' }}

jobs:
  requirements:
    name: Requirements
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        vars: [REGISTRY, REGISTRY_ACCOUNT, REGISTRY_REPO, REGISTRY_REPO_TAG_CACHE_NAME, REGISTRY_PLATFORMS]

    steps:
      - name: Check if variable exist
        run: |
          if [[ -z ${!VARNAME} ]]; then
            echo "Variable \"${VARNAME}\" not found. Please create the variable under \"Repository variables\" \(https://github.com/${{ github.REPOSITORY}}/settings/variables/actions\)."
            exit 1
          fi
        env:
          VARNAME: "${{ matrix.vars }}"

  setup-build-push:
    name: Docker build & push
    runs-on: ubuntu-latest
    needs:
      - requirements

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Load selfoss.${{ env.SOFTWARE_BUILD }} file
        id: selfoss
        run: |
          set -a
          source selfoss.${{ env.SOFTWARE_BUILD }}
          set +a

          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "SHA256_HASH=$SHA256_HASH" >> $GITHUB_OUTPUT
          echo "APP_DL_PATH=$URL" >> $GITHUB_OUTPUT

      - name: Display vars from selfoss.${{ env.SOFTWARE_BUILD }} file
        run: |
          echo "Version: ${{ steps.selfoss.outputs.VERSION }}"
          echo "Hash: ${{ steps.selfoss.outputs.SHA256_HASH }}"
          echo "URL: ${{ steps.selfoss.outputs.APP_DL_PATH }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd  # v4.0.0

      - name: Login to Docker Hub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121  # v4.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create tag list for docker image
        id: tags
        run: |
          if [ "${{ github.event.release.prerelease }}" = true ]; then
            echo "docker=${{ env.REGISTRY_ACCOUNT }}/${{ env.REGISTRY_REPO }}:${{ github.ref_name }}" >> $GITHUB_OUTPUT

          elif [ ! -z "${{ github.event.release.tag_name }}" ]; then
            echo "docker=${{ env.REGISTRY_ACCOUNT }}/${{ env.REGISTRY_REPO }}:latest, ${{ env.REGISTRY_ACCOUNT }}/${{ env.REGISTRY_REPO }}:${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT

          elif [ "${{ env.SOFTWARE_BUILD }}" == "snapshot" ]; then
            echo "docker=${{ env.REGISTRY_ACCOUNT }}/${{ env.REGISTRY_REPO }}:${{ steps.selfoss.outputs.VERSION }}" >> $GITHUB_OUTPUT

          else
            echo "docker=${{ env.REGISTRY_ACCOUNT }}/${{ env.REGISTRY_REPO }}:${{ github.ref_name }}" >> $GITHUB_OUTPUT

          fi

      - name: Build and push
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294  # v7.0.0
        with:
          context: .
          file: Dockerfile
          push: false
          build-args: |
            APP_FILE_HASH=${{ steps.selfoss.outputs.SHA256_HASH }}
            APP_DL_PATH=${{ steps.selfoss.outputs.APP_DL_PATH }}
          tags: ${{ steps.tags.outputs.docker }}
          platforms: ${{ env.REGISTRY_PLATFORMS }}
          cache-from: type=registry,ref=${{ env.REGISTRY_ACCOUNT }}/${{ env.REGISTRY_REPO }}:${{ env.REGISTRY_REPO_TAG_CACHE_NAME }}
          cache-to: type=registry,ref=${{ env.REGISTRY_ACCOUNT }}/${{ env.REGISTRY_REPO }}:${{ env.REGISTRY_REPO_TAG_CACHE_NAME }},mode=max

      - name: Update Docker Repository Description
        uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa  # v5.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.REGISTRY_ACCOUNT }}/${{ env.REGISTRY_REPO }}
          readme-filepath: ./README-dockerhub.md
          short-description: "The ultimate multi-purpose RSS reader, data stream, mash-up, aggregation web application"
