---
name: Manage - Sync branches

"on":
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'


permissions:
  contents: read


jobs:
  update_external_airflow_fork:
    name: Sync branch archive with origin
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Generate app token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859  # v3.0.0
        id: generate-token
        with:
          app-id: ${{ secrets.GH_APP_SRP_ID }}
          private-key: ${{ secrets.GH_APP_SRP_PRIVATE_KEY }}

      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          fetch-depth: 0

      - name: Synchronize the given branch
        uses: TobKed/github-forks-sync-action@2fb78daa46a630ff56455a63dec51ff00ba56e23  # v0.4.0
        with:
          github_token: ${{ steps.generate-token.outputs.token }}
          upstream_repository: hardware/selfoss
          target_repository: ${{ github.repository }}
          upstream_branch: master
          target_branch: archive
          force: false
          tags: false
