---
name: Tools - Docker Build Test

"on":
  workflow_dispatch:
  pull_request:
    branches:
      - "master"
    paths:
      - '**Dockerfile'

permissions:
  contents: read

env:
  REGISTRY_PLATFORMS: ${{ vars.REGISTRY_PLATFORMS }}
  SOFTWARE_BUILD: 'release'

jobs:
  docker-build-image:
    name: Docker Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Load selfoss.${{ env.SOFTWARE_BUILD }} file
        id: selfoss
        run: |
          set -a
          source selfoss.${{ env.SOFTWARE_BUILD }}
          set +a

          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "SHA256_HASH=$SHA256_HASH" >> $GITHUB_OUTPUT
          echo "APP_DL_PATH=$URL" >> $GITHUB_OUTPUT

      - name: Display vars from selfoss.${{ env.SOFTWARE_BUILD }} file
        run: |
          echo "Version: ${{ steps.selfoss.outputs.VERSION }}"
          echo "Hash: ${{ steps.selfoss.outputs.SHA256_HASH }}"
          echo "URL: ${{ steps.selfoss.outputs.APP_DL_PATH }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd  # v4.0.0

      - name: Build docker image
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f  # v7.1.0
        with:
          context: .
          file: ./Dockerfile
          push: false
          platforms: ${{ env.REGISTRY_PLATFORMS }}
          build-args: |
            APP_FILE_HASH=${{ steps.selfoss.outputs.SHA256_HASH }}
            APP_DL_PATH=${{ steps.selfoss.outputs.APP_DL_PATH }}
