---
name: Upload new certificate

"on":
  pull_request:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


env:
  GH_ACTOR: ${{ github.actor }}
  # GH_ACTOR: "dependabot[bot]"
  
permissions:
  contents: write
  pull-requests: write

jobs:
  check:
    name: Check new certificates
    runs-on: ubuntu-latest

    steps:
      - name: Get repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          ref: ${{ github.head_ref }}

      - name: Check file name and location
        shell: pwsh
        run: |
          
          $files = Get-ChildItem -Path "upload" -Filter "*.cer" | Select -ExpandProperty FullName


          foreach ($file in $files) {

            $cert = [System.Security.Cryptography.X509Certificates.X509Certificate2]::new($file)

            if ($cert.Issuer -match 'CN=([^,]+)') {
                $cn = $Matches[1]
            }
            elseif ($cert.Issuer -match 'O=([^,]+)') {
                $ou = $Matches[1]
            }
            elseif ($cert.Issuer -match 'C=([^,]+)') {
                $c = $Matches[1]
            }
            elseif ($cert.Issuer -match 'DC=([^,]+)') {
                $dc = $Matches[1]
            }
            else {
                $o = "Various"
            }

            #####

            $CertCn = (($cert.Issuer.Split(','))[0]).split('=')[1]
            $certOrg = (($cert.Issuer.Split(','))[1]).split('=')[1]

            $FolderNameYear= $cert.NotBefore.Year
            $FileNameThumbprint = $cert.Thumbprint
            $fileExtension = [System.IO.Path]::GetExtension($file).Trim(".")

            #####

            $bc = $cert.Extensions | Where-Object { $_ -is [System.Security.Cryptography.X509Certificates.X509BasicConstraintsExtension] } | Select-Object -First 1

            if ($bc.CertificateAuthority) {
                Write-Output "CA Certificate`n"
            }
            else {
                Write-Output "Server Certificate`n"
                exit 1
            }
            
            #####

            [array] $characterMap = @(
                @(' ','_'),
                @('<','-'),
                @('>','-'),
                @(':','-'),
                @('/','-'),
                @('\\','-'),
                @('\|','-'),
                @('\?','-'),
                @('\*','-'),
                @('\.$','')
             )

            $characterMap | ForEach-Object {
                $CertCn = $CertCn -replace($_[0],$_[1])
                $certOrg = $certOrg -replace($_[0],$_[1])
            }

            #####

            if ($cert.Issuer -eq $cert.Subject) {
                #
                $basePath = "roots"
            }
            else {
                #
                $basePath = "intermediaries"
            }

            $targetPath = Join-Path $basePath $certOrg
            $targetPath = Join-Path $targetPath $FolderNameYear
            $filename = "$($CertCn)_$($FileNameThumbprint).$fileExtension"
            Write-Output "`n$targetPath`n"
            New-Item -ItemType Directory -Path $targetPath -Force -Verbose
            $destination = Join-Path $targetPath $filename

            # Write-Output "$targetPath/$($CertCn)_$($FileNameThumbprint).$fileExtension"
            
            Write-Output "`nDestination"
            Write-Output "$destination`n"

            Write-Output "`nFile"
            Write-Output "$file`n"
            
            Write-Output "move"
            Write-Host "Source: $file"
            Write-Host "Target: $GITHUB_WORKSPACE/$destination"
            
            if (Test-Path -LiteralPath $file) {
                Move-Item -LiteralPath $file -Destination $destination -Force -Verbose
                Write-Host "Moved successfully"

                # Set global options
                # https://git-scm.com/docs/git-config
                # https://medium.com/@shahbishwa21/automate-daily-commits-with-random-content-using-github-actions-804736759c1d
                git config --local user.email "${{ env.GH_ACTOR }}@users.noreply.github.com"
                git config --local user.name "${{ env.GH_ACTOR }}"

                # Add contents of new or changed files to the index
                # https://git-scm.com/docs/git-add
                # git add $destination
                git add -A

                # Create a new commit containing the current contents of the index and the given log message describing the changes
                # https://git-scm.com/docs/git-commit
                git commit -m "Added $(Split-Path $destination -Leaf)"

                # Update remote refs along with associated objects
                # https://git-scm.com/docs/git-push
                git push origin HEAD

            } else {
                Write-Host "File not found!"
                exit 1
            }

            git status
          }

#      - name: Create Pull Request
#        uses: devops-infra/action-pull-request@b2895bff2ff66579f6704d717a1ea75fad919e84
#        with:
#          github_token: ${{ secrets.NSP_GH_TOKEN }}
#          source_branch: ${{ github.ref_name }}
#          target_branch: master
#          title: "Automated certificate upload"
#          body: |
#            This PR was automatically created after processing uploaded certificates.
#            
#            - Certificates were validated
#            - Files were reorganized into CA structure
