---
name: Upload new certificate

"on":
  pull_request:
    branches: ["master"]
    paths:
      - "upload/*.cer"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


env:
  GH_ACTOR: ${{ github.actor }}
  # GH_ACTOR: "dependabot[bot]"
  
permissions:
  contents: write
  pull-requests: write

jobs:
  check:
    name: Check new certificates
    runs-on: ubuntu-latest

    steps:
      - name: Get repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1
        with:
          ref: ${{ github.head_ref }}

      - name: Check file name and location
        shell: pwsh
        run: |

          # Declaration and initialization of variables
          [string] $strFolderBasePath = ""
          [string] $strTargetPath = ""
          [string] $strFilename = ""
          [string] $strDestination = ""
          [string] $strFolderNameYear = ""
          [string] $strFileNameThumbprint = ""
          [string] $strFileExtension = ""

          [array] $characterMap = @(
            @(' ','_'),
            @('<','-'),
            @('>','-'),
            @(':','-'),
            @('/','-'),
            @('\\','-'),
            @('\|','-'),
            @('\?','-'),
            @('\*','-'),
            @('\.$','')
          )


          # Set global options
          # https://git-scm.com/docs/git-config
          # https://medium.com/@shahbishwa21/automate-daily-commits-with-random-content-using-github-actions-804736759c1d
          git config --local user.email "${{ env.GH_ACTOR }}@users.noreply.github.com"
          git config --local user.name "${{ env.GH_ACTOR }}"


          # Retrieving files in all directories that have the file types cer, der, and pem
          # The column named Fullname is passed to the loop.            
          Get-ChildItem -Path "upload" -Filter "*.cer" | Select -ExpandProperty Fullname | ForEach-Object {

            #  Declaration and initialization of variables for the loop
            [string] $strFile = $_

            $cert = [System.Security.Cryptography.X509Certificates.X509Certificate2]::new($strFile)

            if ($cert.Issuer -match 'CN=([^,]+)') {
                $cn = $Matches[1]
            }
            elseif ($cert.Issuer -match 'O=([^,]+)') {
                $ou = $Matches[1]
            }
            elseif ($cert.Issuer -match 'C=([^,]+)') {
                $c = $Matches[1]
            }
            elseif ($cert.Issuer -match 'DC=([^,]+)') {
                $dc = $Matches[1]
            }
            else {
                $o = "Various"
            }

            # 
            $CertCn = (($cert.Issuer.Split(','))[0]).split('=')[1]
            $certOrg = (($cert.Issuer.Split(','))[1]).split('=')[1]

            $characterMap | ForEach-Object {
                $CertCn = $CertCn -replace($_[0],$_[1])
                $certOrg = $certOrg -replace($_[0],$_[1])
            }


            #
            $bc = $cert.Extensions | Where-Object { $_ -is [System.Security.Cryptography.X509Certificates.X509BasicConstraintsExtension] } | Select-Object -First 1

            if ($bc.CertificateAuthority) {
                Write-Output "CA Certificate`n"
            }
            else {
                Write-Output "Server Certificate`n"

                Remove-Item -LiteralPath "$strFile" -Confirm:$false

                # Add contents of new or changed files to the index
                # https://git-scm.com/docs/git-add
                git add $strFile

                # Create a new commit containing the current contents of the index and the given log message describing the changes
                # https://git-scm.com/docs/git-commit
                git commit -m "Delete $(Split-Path $strFile -Leaf)"

                #
                continue
            }
            

            if ($cert.Issuer -eq $cert.Subject) {
                #
                $strFolderBasePath = "roots"
            }
            else {
                #
                $strFolderBasePath = "intermediaries"
            }

            #
            $strFolderNameYear = $cert.NotBefore.Year
            $strFileNameThumbprint = $cert.Thumbprint
            $strFileExtension = [System.IO.Path]::GetExtension($strFile).Trim(".")

            $strTargetPath = Join-Path $strFolderBasePath $certOrg
            $strTargetPath = Join-Path $strTargetPath $strFolderNameYear
            $strFilename = "$($CertCn)_$($strFileNameThumbprint).$strFileExtension"
            
            Write-Output "`n$strTargetPath`n"
            New-Item -ItemType Directory -Path $strTargetPath -Force -Verbose
            
            $strDestination = Join-Path $strTargetPath $strFilename

            # Write-Output "$strTargetPath/$($CertCn)_$($strFileNameThumbprint).$strFileExtension"
            
            Write-Output "`nDestination"
            Write-Output "$strDestination`n"

            Write-Output "`nFile"
            Write-Output "$strFile`n"

              
            if (Test-Path -LiteralPath $strDestination) {

              Write-Output "CA Cert bereits vorhanden."
              Remove-Item -LiteralPath "$strFile" -Confirm:$false

              # Add contents of new or changed files to the index
              # https://git-scm.com/docs/git-add
              # git add $strDestination
              git add $strFile

              # Create a new commit containing the current contents of the index and the given log message describing the changes
              # https://git-scm.com/docs/git-commit
              git commit -m "Delete $(Split-Path $strFile -Leaf)"
            }
            else {
            
              Write-Output "move"
              Write-Host "Source: $strFile"
              Write-Host "Target: $strDestination"
            
                Move-Item -LiteralPath $strFile -Destination $strDestination -Force -Verbose
                Write-Host "Moved successfully"

                # Add contents of new or changed files to the index
                # https://git-scm.com/docs/git-add
                # git add $strDestination
                git add -A

                # Create a new commit containing the current contents of the index and the given log message describing the changes
                # https://git-scm.com/docs/git-commit
                git commit -m "Add $(Split-Path $strDestination -Leaf)"
            }

              # Update remote refs along with associated objects
              # https://git-scm.com/docs/git-push
              git push origin HEAD
          }

#      - name: Create Pull Request
#        uses: devops-infra/action-pull-request@b2895bff2ff66579f6704d717a1ea75fad919e84
#        with:
#          github_token: ${{ secrets.NSP_GH_TOKEN }}
#          source_branch: ${{ github.ref_name }}
#          target_branch: master
#          title: "Automated certificate upload"
#          body: |
#            This PR was automatically created after processing uploaded certificates.
#            
#            - Certificates were validated
#            - Files were reorganized into CA structure
